'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8762.
'
Namespace OraWebService
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="perodua_eai_process_inventory_ws_servicePart_processServicePartService_Binder", [Namespace]:="http://VAWBMTD0.perodua.com.my/perodua/eai/process/inventory/ws/servicePart/proce"& _ 
        "ssServicePartService")>  _
    Partial Public Class processServicePartService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://VAWBMTD0.perodua.com.my:4559/ws/perodua.eai.process.inventory.ws.servicePa"& _ 
                "rt:processServicePartService/perodua_eai_process_inventory_ws_servicePart_proces"& _ 
                "sServicePartService_Port"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("perodua_eai_process_inventory_ws_servicePart_processServicePartService_Binder_pro"& _ 
            "cessServicePart", RequestElementName:="processServicePartReqDoc", RequestNamespace:="http://VAWBMTD0.perodua.com.my/perodua/eai/process/inventory/ws/servicePart/proce"& _ 
            "ssServicePartService", ResponseElementName:="processServicePartRespDoc", ResponseNamespace:="http://VAWBMTD0.perodua.com.my/perodua/eai/process/inventory/ws/servicePart/proce"& _ 
            "ssServicePartService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function processServicePart(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/servicePart/Inventory", IsNullable:=true)> ByVal batchID As String, <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/servicePart/Inventory", IsNullable:=true)> ByVal processType As String, <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/servicePart/Inventory", IsNullable:=true)> ByRef msgDesc As String) As <System.Xml.Serialization.XmlElementAttribute("msgCode", [Namespace]:="http://schemas.perodua.com.my/EAI/servicePart/Inventory", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("processServicePart", New Object() {batchID, processType})
            msgDesc = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginprocessServicePart(ByVal batchID As String, ByVal processType As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("processServicePart", New Object() {batchID, processType}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndprocessServicePart(ByVal asyncResult As System.IAsyncResult, ByRef msgDesc As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgDesc = CType(results(1),String)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
