'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8784
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8784.
'
Namespace ValidationWebService
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="perodua_eai_process_inventory_ws_processValidationService_Binder", [Namespace]:="http://services.perodua.com.my/EAI/Inventory/InventoryService/v1/")>  _
    Partial Public Class processValidationService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private eaiHeaderValueField As eaiHeader
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://VAWBMTD0.perodua.com.my:4559/ws/perodua.eai.process.inventory.ws:processVa"& _ 
                "lidationService/perodua_eai_process_inventory_ws_processValidationService_Port"
        End Sub
        
        Public Property eaiHeaderValue() As eaiHeader
            Get
                Return Me.eaiHeaderValueField
            End Get
            Set
                Me.eaiHeaderValueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("eaiHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("perodua_eai_process_inventory_ws_processValidationService_Binder_processValidatio"& _ 
            "n", RequestElementName:="processValidationReqDoc", RequestNamespace:="http://services.perodua.com.my/EAI/Inventory/InventoryService/v1/", ResponseElementName:="processValidationRespDoc", ResponseNamespace:="http://services.perodua.com.my/EAI/Inventory/InventoryService/v1/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function processValidation( _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal batchID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal scannerID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal processType As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal processCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal cdioId As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal cdioNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal pillingOrder As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal grossWeight As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forceCDIOStatus As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forceCDIOReasonID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forceModuleStatus As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forceModuleReasonID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal moduleID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal moduleNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal extPartNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal extPartNoSfx As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal extPartNoSeq As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal qtyBox As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal manufactureCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal supplierCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal supplierPlantCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal ShippingDock As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal beforePackingRouting As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal receivingCompanyCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal receivingPlantCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal receivingDockCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal packingRoutingCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal granterCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal orderType As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal kanbanClassification As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal mros As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal orderNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal deliveryCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal deliveryNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal backNumber As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal runoutFlag As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal boxType As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal branchNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal address As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal packingDate As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal katashikiJerseyNumber As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal lotNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal moduleCategory As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal partBranchNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal dummy As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal versionNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal pdioID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal pdioNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal dockCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal pdioOrderType As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal transporterID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal vendorID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal laneID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal tier As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal p2PartNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal p2PartSeqNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal p2BackNo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal p2QtyOrder As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal deliveryType As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal orgID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal deliveryDate As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal supplyBy As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal supplyDate As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal unpackBy As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal unpackDate As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal robbingBy As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal robbingDate As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal rcvBy As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal rcvDate As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal createdBy As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal onOffLineFlag As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal scanBy As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal scanDate As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forcePDIOStatus As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forcePDIOReasonID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forceExtStatus As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forceExtReasonID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forceP2Status As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal forcep2ReasonID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal scannerScreenCode As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByVal shopID As String,  _
                    <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> ByRef msgDesc As String) As <System.Xml.Serialization.XmlElementAttribute("msgCode", [Namespace]:="http://schemas.perodua.com.my/EAI/Inventory/Inventory/v1/", IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("processValidation", New Object() {batchID, scannerID, processType, processCode, cdioId, cdioNo, pillingOrder, grossWeight, forceCDIOStatus, forceCDIOReasonID, forceModuleStatus, forceModuleReasonID, moduleID, moduleNo, extPartNo, extPartNoSfx, extPartNoSeq, qtyBox, manufactureCode, supplierCode, supplierPlantCode, ShippingDock, beforePackingRouting, receivingCompanyCode, receivingPlantCode, receivingDockCode, packingRoutingCode, granterCode, orderType, kanbanClassification, mros, orderNo, deliveryCode, deliveryNo, backNumber, runoutFlag, boxType, branchNo, address, packingDate, katashikiJerseyNumber, lotNo, moduleCategory, partBranchNo, dummy, versionNo, pdioID, pdioNo, dockCode, pdioOrderType, transporterID, vendorID, laneID, tier, p2PartNo, p2PartSeqNo, p2BackNo, p2QtyOrder, deliveryType, orgID, deliveryDate, supplyBy, supplyDate, unpackBy, unpackDate, robbingBy, robbingDate, rcvBy, rcvDate, createdBy, onOffLineFlag, scanBy, scanDate, forcePDIOStatus, forcePDIOReasonID, forceExtStatus, forceExtReasonID, forceP2Status, forcep2ReasonID, scannerScreenCode, shopID})
            msgDesc = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginprocessValidation( _
                    ByVal batchID As String,  _
                    ByVal scannerID As String,  _
                    ByVal processType As String,  _
                    ByVal processCode As String,  _
                    ByVal cdioId As String,  _
                    ByVal cdioNo As String,  _
                    ByVal pillingOrder As String,  _
                    ByVal grossWeight As String,  _
                    ByVal forceCDIOStatus As String,  _
                    ByVal forceCDIOReasonID As String,  _
                    ByVal forceModuleStatus As String,  _
                    ByVal forceModuleReasonID As String,  _
                    ByVal moduleID As String,  _
                    ByVal moduleNo As String,  _
                    ByVal extPartNo As String,  _
                    ByVal extPartNoSfx As String,  _
                    ByVal extPartNoSeq As String,  _
                    ByVal qtyBox As String,  _
                    ByVal manufactureCode As String,  _
                    ByVal supplierCode As String,  _
                    ByVal supplierPlantCode As String,  _
                    ByVal ShippingDock As String,  _
                    ByVal beforePackingRouting As String,  _
                    ByVal receivingCompanyCode As String,  _
                    ByVal receivingPlantCode As String,  _
                    ByVal receivingDockCode As String,  _
                    ByVal packingRoutingCode As String,  _
                    ByVal granterCode As String,  _
                    ByVal orderType As String,  _
                    ByVal kanbanClassification As String,  _
                    ByVal mros As String,  _
                    ByVal orderNo As String,  _
                    ByVal deliveryCode As String,  _
                    ByVal deliveryNo As String,  _
                    ByVal backNumber As String,  _
                    ByVal runoutFlag As String,  _
                    ByVal boxType As String,  _
                    ByVal branchNo As String,  _
                    ByVal address As String,  _
                    ByVal packingDate As String,  _
                    ByVal katashikiJerseyNumber As String,  _
                    ByVal lotNo As String,  _
                    ByVal moduleCategory As String,  _
                    ByVal partBranchNo As String,  _
                    ByVal dummy As String,  _
                    ByVal versionNo As String,  _
                    ByVal pdioID As String,  _
                    ByVal pdioNo As String,  _
                    ByVal dockCode As String,  _
                    ByVal pdioOrderType As String,  _
                    ByVal transporterID As String,  _
                    ByVal vendorID As String,  _
                    ByVal laneID As String,  _
                    ByVal tier As String,  _
                    ByVal p2PartNo As String,  _
                    ByVal p2PartSeqNo As String,  _
                    ByVal p2BackNo As String,  _
                    ByVal p2QtyOrder As String,  _
                    ByVal deliveryType As String,  _
                    ByVal orgID As String,  _
                    ByVal deliveryDate As String,  _
                    ByVal supplyBy As String,  _
                    ByVal supplyDate As String,  _
                    ByVal unpackBy As String,  _
                    ByVal unpackDate As String,  _
                    ByVal robbingBy As String,  _
                    ByVal robbingDate As String,  _
                    ByVal rcvBy As String,  _
                    ByVal rcvDate As String,  _
                    ByVal createdBy As String,  _
                    ByVal onOffLineFlag As String,  _
                    ByVal scanBy As String,  _
                    ByVal scanDate As String,  _
                    ByVal forcePDIOStatus As String,  _
                    ByVal forcePDIOReasonID As String,  _
                    ByVal forceExtStatus As String,  _
                    ByVal forceExtReasonID As String,  _
                    ByVal forceP2Status As String,  _
                    ByVal forcep2ReasonID As String,  _
                    ByVal scannerScreenCode As String,  _
                    ByVal shopID As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("processValidation", New Object() {batchID, scannerID, processType, processCode, cdioId, cdioNo, pillingOrder, grossWeight, forceCDIOStatus, forceCDIOReasonID, forceModuleStatus, forceModuleReasonID, moduleID, moduleNo, extPartNo, extPartNoSfx, extPartNoSeq, qtyBox, manufactureCode, supplierCode, supplierPlantCode, ShippingDock, beforePackingRouting, receivingCompanyCode, receivingPlantCode, receivingDockCode, packingRoutingCode, granterCode, orderType, kanbanClassification, mros, orderNo, deliveryCode, deliveryNo, backNumber, runoutFlag, boxType, branchNo, address, packingDate, katashikiJerseyNumber, lotNo, moduleCategory, partBranchNo, dummy, versionNo, pdioID, pdioNo, dockCode, pdioOrderType, transporterID, vendorID, laneID, tier, p2PartNo, p2PartSeqNo, p2BackNo, p2QtyOrder, deliveryType, orgID, deliveryDate, supplyBy, supplyDate, unpackBy, unpackDate, robbingBy, robbingDate, rcvBy, rcvDate, createdBy, onOffLineFlag, scanBy, scanDate, forcePDIOStatus, forcePDIOReasonID, forceExtStatus, forceExtReasonID, forceP2Status, forcep2ReasonID, scannerScreenCode, shopID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndprocessValidation(ByVal asyncResult As System.IAsyncResult, ByRef msgDesc As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            msgDesc = CType(results(1),String)
            Return CType(results(0),String)
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/common/soap/v1/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://schemas.perodua.com.my/EAI/common/soap/v1/", IsNullable:=false)>  _
    Partial Public Class eaiHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private fromField As String
        
        Private toField As String
        
        Private appIdField As String
        
        Private msgTypeField As String
        
        Private msgIdField As String
        
        Private correlationIdField As String
        
        Private timestampField As String
        
        '''<remarks/>
        Public Property from() As String
            Get
                Return Me.fromField
            End Get
            Set
                Me.fromField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [to]() As String
            Get
                Return Me.toField
            End Get
            Set
                Me.toField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property appId() As String
            Get
                Return Me.appIdField
            End Get
            Set
                Me.appIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property msgType() As String
            Get
                Return Me.msgTypeField
            End Get
            Set
                Me.msgTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property msgId() As String
            Get
                Return Me.msgIdField
            End Get
            Set
                Me.msgIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property correlationId() As String
            Get
                Return Me.correlationIdField
            End Get
            Set
                Me.correlationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property timestamp() As String
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
    End Class
End Namespace
